"""
Django settings for Core project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fubpcac&%r&bpm-1#0gl0iv7i5mh!6ui3(mng%2+_bl=zkqymp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # new
    'Auth',
    'allauth',  # new
    'allauth.account',  # new
    'allauth.socialaccount',
    'allauth.socialaccount.providers.linkedin_oauth2',  # new
    'allauth.socialaccount.providers.twitter',  # new
    'allauth.socialaccount.providers.facebook',  # new
    'allauth.socialaccount.providers.instagram',
    'allauth.socialaccount.providers.pinterest',
    'allauth.socialaccount.providers.reddit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]


ROOT_URLCONF = 'Core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# config/settings.py
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 1

ACCOUNT_EMAIL_VERIFICATION = 'none'

LOGIN_REDIRECT_URL = '/home'

# Linkedin Authentication Setting
SOCIALACCOUNT_PROVIDERS = {
    # 'facebook': {
    #     'METHOD': 'oauth2',  # Set to 'js_sdk' to use the Facebook connect SDK
    #     'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
    #     'SCOPE': ['email', 'public_profile'],
    #     'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
    #     'INIT_PARAMS': {'cookie': True},
    #     'FIELDS': [
    #         'id',
    #         'first_name',
    #         'last_name',
    #         'middle_name',
    #         'name',
    #         'name_format',
    #         'picture',
    #         'short_name'
    #     ],
    #     'EXCHANGE_TOKEN': True,
    #     'LOCALE_FUNC': 'path.to.callable',
    #     'VERIFIED_EMAIL': False,
    #     'VERSION': 'v13.0',
    #     'GRAPH_API_URL': 'https://graph.facebook.com/v13.0',
    # },
    # 'twitter': {
    #
    #     'APP': {
    #         'Provider': 'Twitter',
    #         'Name': 'Twitter',
    #         'client_id': '9oHQO3i5iuWzdZuOMxFe5veFk',
    #         'secret': 'X7ea3qV9zqdjbwnFGLRcsb4l4rAgsJNFTv9vBSbbLfHwazBC75',
    #         'key': '',
    #
    #     }
    # },
    "linkedin_oauth2": {
        "SCOPE": ["openid", "profile", "w_member_social", "email"],

        "EXCHANGE_TOKEN": True,
        'APP': {
            'client_id': '86mdxh6sotr11y',
            'secret': 'xwlI7v10GsIHZyPx',
            'key': '',
            "redirect_uri": "http://localhost:8001/accounts/linkedin_oauth2/login/callback/"
        }
    },
    # 'pinterest': {
    #     'SCOPE': ['read_public', 'write_public'],
    #     'METHOD': 'oauth2',
    #     "API_VERSION": "v5",
    #     'VERIFIED_EMAIL': True
    # },
    # 'instagram': {
    #     'SCOPE': ['user_profile'],  # The scope for Instagram API access
    #     'AUTH_PARAMS': {'auth_type': 'reauthenticate'},  # Additional authentication parameters
    #     'METHOD': 'oauth2',  # The authentication method (oauth2 in this case)
    #     'VERIFIED_EMAIL': False,  # Whether to verify email or not
    # },
    # 'reddit': {
    #     'AUTH_PARAMS': {'duration': 'permanent'},
    #     'SCOPE': ['identity', 'submit'],
    #     'USER_AGENT': 'django:myappid:1.0 (by /u/yourredditname)',
    # }
}

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
SITE_DOMAIN = 'localhost'